config/routes.rb
Rails.application.routes.draw do
  resources :user_notifications
root to: 'home#show'
resources :users
resources :writings
resources :publishedworks

get "/sign_up", to: "users#new", as: "sign_up"

get "/login", to: "sessions#new"

post "/sessions", to: "sessions#create"

post "/logout", to: "sessions#destroy"

get "/home", to: "home#show"

get "/artists", to: "artists#show"

get "/writers", to: "writers#show"

# post "/publishedworks/new"

# get "/gallery/:user_id", to: "gallery#show"

# get "/works", to: "publishedworks#show"


# get "/users/:id/gallery", to: "gallery#show"

get "/users/:id/gallery", to: "users#showGal"

get "/users/:id/writings", to: "users#showWrit"

delete "/users/:user_id/writings", to: "writings#destroy", as: "destroy_users_writing"

post "/users/:id/connect", to: "users#connect", as: "connect"

get "/request", to: "users#sendReq", as: "request"

get "/users/:id/drawings/new", to: "users#newDraw", as: "draw"





# # commenting out for now - old writNew routes
# get "/users/:id/writings/edit", to: "users#writNew"

# get "/writers/new", to: "writers#new", as: "writings"

# post "/writers/", to: "writers#create"





end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :writings
	has_many :drawings, :dependent => :destroy
  validates :email, uniqueness: true
  validates :email, presence: true
  validates :username, uniqueness: true
  validates :username, presence: true
  validates :about, length: { maximum: 300 }
  validates :tech, length: { maximum: 300 }

	has_secure_password

	def self.confirm(params)
    @user = User.find_by({email: params[:email]})
    @user.try(:authenticate, params[:password])
  end

has_attached_file :avatar,
  :styles => { :medium => "250x200>", :thumb => "125x125#" },
  :default_url => "/images/default.jpg"

  validates_attachment :avatar,
                       :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] },
                       :size => { :in => 0..1000.kilobytes }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index 
		@users = User.all
		#optional
		render :users
	end

	def new
		@user = User.new
		render :new
	end

	def show
		 @user = User.find(params[:id])
     # @user = User.find(user_params)

     
    # render :show
	end

   #this method will send an email to the user
  def connect 
    @user = User.find(params[:id])
    p "Sent"
    #if the connect method is called, send an email to that user
     respond_to do |format|
      UserMailer.notification_email(@user).deliver_now
      format.html { redirect_to(request_path, :notice => 'User has successfully been sent an email.') }
      # format.json { render json: @user, status: :created, location: @user }
    # else
    #   format.html { render action: "show" }
    #   format.json { render json: @user.errors, status: :unprocessable_entity}
    end
    
  

    # redirect_to request_path
  end

	def showGal
		 @user = User.find(params[:id])
		 	@drawings = @user.drawings
    render :showGal
	end

	def showWrit
    @users = User.all
			 @user = User.find(params[:id])
       # @writing = Writing.new(user)
       @writings = @user.writings
    render :showWrit
  end


  #method for creating new user
	def create
		@user = User.new(user_params)
    p user_params
		if @user.save 
      session[:user_id] = @user.id
			redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages
      redirect_to sign_up_path
		end

			# #testing creation of images
		 #   respond_to do |format|
   #    if @user.save

   #      if params[:images]
   #        # The magic is here ;)
   #        params[:images].each { |image|
   #          @user.drawings.create(image: image)
   #        }
   #      end
   #    end

    # end

	end

  def writNew
    render :newWrit
  end

	def edit
  	@user = User.find(params[:id])
  end

  def update

  		#test for update
  		user_id = params[:id]
  		@user = User.find(user_id)
  		updated_attributes = params.require(:user).permit(:first_name, :last_name, :about, :tech, :avatar, :image)
  	if @user.update_attributes(updated_attributes)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @user.drawings.create(image: image)
          }
          # redirect_to @user
        end


     # old code
  	# user_id = params[:id]
  	# user = User.find(user_id)
  	# updated_attributes = params.require(:user).permit(:about, :tech, :avatar)
  	# user.update_attributes(updated_attributes)
  	# redirect_to user
    redirect_to @user
  end
end

def newDraw
  #test for update
      user_id = params[:id]
      @user = User.find(user_id)
      # updated_attributes = params.require(:user).permit(:about, :tech, :avatar, :image)
    # if @user.update_attributes(updated_attributes)
        if params[:images]
          # The magic is here ;)
          params[:images].each { |image|
            @user.drawings.create(image: image)
          }
          redirect_to @user
        end
    # redirect_to @user
  # end
   # render :newDraw 
end

# destroy writings
def destroy
  @user = User.find(params[:id])
  id = params[:id]
  # @user.writings
  # :id is being set to user.id
   writings =  Writing.find(:id)
    if current_user.writings.include? writing
      writing.destroy
      redirect_to user_path(@user)
  end
end

	private
	def user_params
		params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :age, :person, :sex)
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="jumbotron">
  <h1 class="jumbotron-text">Update</h1>
</div>

<%= form_for @user, :url => user_path, :html => { :multipart => true } do |f| %>
<div class = "container">
<div class = "row">
<form role ="form">
<div class="col-lg-10">
	  <br>

       <div class="form-group">
                    <label for="InputFirst">First Name</label>
                    <div class="input-group">
                             <%= f.text_field :first_name, placeholder: "First Name" do %>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <% end %>
                <br>
                 <div class="form-group">
                    <label for="InputLast">Last Name</label>
                    <div class="input-group">
                             <%= f.text_field :last_name, placeholder: "Last Name" do %>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <% end %>

	  <div class="form-group">
    About: <%= f.text_area :about, class: "form-control1", placeholder: "About" %>
    </div>
    <br>
    <div class="text-field">
    Technologies/Softwares you use: <%= f.text_area :tech, class: "form-control1", placeholder: "If you're an artist, please input the technologies that you use " %>
    </div>
    <br>
    <!--Allow users to toggle for specific elements hidden -->
    <div class = "input-group">
    Show Gender on Profile Page: 
    <form action="">
<input type="checkbox" class="checkbox1" name="Gender" value="Yes">Yes   
<input type="checkbox" class="checkbox2" name="Gender" value="No">No 
</form>
    </div>
    <% if current_user.person == 'Artist' %>
    <!--will update with gallery -->
  <div class="control-group"> Drawing:
      <!-- This is where the magic happens -->
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>
    <%end%>

    <span class ="selector-text"> Update your Avatar:</span> <%= f.file_field :avatar, class: "form-control" %><br>
    <%= f.submit "Update", class: "btn btn-info" %>
    </div>
    </form>
    </div>
    </div>
    <% end %>
    

app/views/users/new.html.erb
<%= form_for :user, url: "/users", method: "post" do |f| %>
<body class="signuppage">
<div class="container">
<div class="sign-up">
    <div class="row">
        <form role="form">
            <div class="col-lg-6">
            <h3> Sign Up </h3>
                <div class="form-group">
                    <label for="InputName">Enter Username*</label>
                    <div class="input-group">
                        <%= f.text_field :username, placeholder: "Username" do %> 
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span> 
                    </div>
                </div>
                <%end%>
                <br>
                <div class="form-group">
                    <label for="InputEmail">Enter Email*</label>
                    <div class="input-group">
                      <%= f.text_field :email, placeholder: "Email" do%>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <%end%>
                <div class="form-group">
                    <label for="InputFirst">First Name</label>
                    <div class="input-group">
                             <%= f.text_field :first_name, placeholder: "First Name" do %>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <% end %>
                   <div class="form-group">
                    <label for="InputLast">Last Name</label>
                    <div class="input-group">
                             <%= f.text_field :last_name, placeholder: "Last Name" do %>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <% end %>
                <div class="form-group">
                    <label for="InputAge">Enter Age</label>
                    <div class="input-group">
                        <%= f.number_field :age, placeholder: "Age", min:13, max:100 do%>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <%end%>
                <br>
                <label for="InputPassword">Enter Password*</label>
                <br>
                <%= f.password_field :password, placeholder: "Password" %>
                <br>
                <label for="ChooseArtist">Please select if you are signing up as a writer or an artist:</label>
                <br>
                 <%= f.select :person, options_for_select([["Artist", "Artist"], ["Writer", "Writer"]]) %>
                <br>
                <label for="ChooseGender">Please specify your Gender:</label>
                <br>
                 <%= f.select :sex, options_for_select([["Male", "Male"], ["Female", "Female"]]) %>
                 <br>
                 <div class= "asterisk"><strong>* Required Field</strong></div>
                 <div class="Sign-up">
                <%= f.submit "Sign Up", class: "btn btn-info" %>
                <div>


            </div>
        </form>
    </div>
    </div>
</div>
<%end%>
</body>

app/views/users/newDraw.html.erb
<div class="jumbotron">
  <h1 class="jumbotron-text">Add Drawing</h1>
</div>

<%= form_for @user, :url => user_path, :html => { :multipart => true } do |f| %>
    <!--will update with gallery -->
  <div class="control-group"> Drawing:
      <!-- This is where the magic happens -->
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </div>

     <%= f.submit "Update" %>
    <% end %>

app/views/users/newWrit.html.erb
<div class="jumbotron">
  <h1>New Writing Post Form</h1>
</div>

app/views/users/sendReq.html.erb
<div class="jumbotron">
  <h1>Request Sent</h1>
</div>

<p> Thanks, we've sent a request to this user. You'll hear back from them if they're intereseted. </p>

app/views/users/show.html.erb
<div class="jumb">
  <img class = "image-bubble" src="/images/Collab_bubble_purple.png">
  <h5> <%= @user.username %>'s Profile </h5>
</div>


<!--Navbar -->
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">


	<div class="row">

		<div class="col-md-12">

			<div class="panel panel-default">

                <div class="panel-heading">

                    <span class="panel-title">

						<div class="pull-left">
							<ul class="nav nav-tabs">
								<li class="active"><a href="" data-toggle="tab">Profile</a></li>
								<li class="inactive"><a href="/users/<%= @user.id%>/gallery"><i class="glyphicon glyphicon-picture"></i> Gallery</a></li>
								<li class="inactive"><a href="/users/<%= @user.id%>/writings"><i class="glyphicon glyphicon-pencil"></i> Writings</a></li>
							</ul>
						</div>

                            <div class="btn-group pull-right">
                                    <% if current_user == @user %>
                                    <%= button_to edit_user_path(@user), :class => "btn btn-default dropdown-toggle", method: "get" do %> Settings <i class="glyphicon glyphicon-cog"></i>
                                    <%end%>
                                    <%end%>
                                <ul class="dropdown-menu" style="width:300px; padding:0px;">

										<li>


												    <div class="panel panel-default" id="preferences" style="margin:0px;">

									    <div class="panel-body">

    										<div class="form-group">

											</div>

										</div>



												</div>

										</li>
									</ul>


                            </div>

						<div class="clearfix"></div>

					</span>

				</div>

                <div class="panel-body">
						<!--Insert Panel content here-->

					 <%= image_tag @user.avatar.url(:thumb) %>
						<br>
    		    Name: <%= @user.first_name %> <%= @user.last_name %>
<br>
Age: <%= @user.age %>
<br>
Writer or Artist: <%= @user.person %>
<br>
Email: <%= @user.email %>
<br>
<div class="hidden">
Gender: <%= @user.sex %>
</div>
<p>About: <%= @user.about %> </p>

<p>Technologies Used: <%= @user.tech %> </p>

<% if current_user != @user %>
<p> Interested in collaborating with <%=@user.first_name %>? Send a request email to get in contact with them. </p>
<%= button_to connect_path(@user), :class => "btn btn-info", method: :post, data: { confirm: "Do you want to send a request to this user?" } do %> Contact <i class="glyphicon glyphicon-envelope"></i>
<%end%>
<%end%>


                </div>

            </div>

		</div>

    </div>

</div>

app/views/users/showGal.html.erb
<div class="jumb">
  <img class = "image-bubble" src="/images/Collab_bubble_purple.png">
  <h5> <%= @user.username %>'s Gallery</h5>
</div>



<link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">


	<div class="row">

		<div class="col-md-12">

			<div class="panel panel-default">

                <div class="panel-heading">

                    <span class="panel-title">

						<div class="pull-left">
							<ul class="nav nav-tabs">
								<li class="inactive"><%= link_to "Profile", user_path(@user) %> </li>
								<li class="active"><a href=""><i class="glyphicon glyphicon-picture"></i> Gallery</a></li>
								<li class="inactive"><a href="/users/<%= @user.id%>/writings"><i class="glyphicon glyphicon-pencil"></i> Writings</a></li>
							</ul>
						</div>

                            <div class="btn-group pull-right">
                                    <% if current_user == @user %>
                                    <%= button_to edit_user_path(@user), :class => "btn btn-default dropdown-toggle", method: "get" do %> Settings <i class="glyphicon glyphicon-cog"></i>
                                    <%end%>
                                    <%end%>
                                <ul class="dropdown-menu" style="width:300px; padding:0px;">

										<li>


												    <div class="panel panel-default" id="preferences" style="margin:0px;">

									    <div class="panel-body">

    										<div class="form-group">

											</div>

										</div>



												</div>

										</li>
									</ul>


                            </div>

						<div class="clearfix"></div>

					</span>

				</div>

                <div class="panel-body">
                <div class="centered">
                <% if current_user == @user %>
                   <%= button_to edit_user_path, :class => "btn btn-info", method: "get" do %> Add a New Drawing Post
									<%end%>
									<% end %>
                </div>

                <!--trying to render drawing from each user -->
				<% if @user.person == "Artist" %>
				<div class="row">
  <ul class="thumbnails files">

  <!--for brian -->
  <% if @user.email == "bgabot89@gmail.com" %>
  <div class="thumbnail">
 	<img src="/images/ahri-ai.png">
 	</div>
	<div class="thumbnail">
 	<img src="/images/Soonsmall.png">
 	</div>
 	<% end %>
  <% @drawings.each do |pic| %>
    <li class="span3" id="drawing_<%= pic.id %>">
    <div class="thumbnail">
      <%= image_tag pic.image.url %>
      <div class="caption">

        <p style="text-align: center;">

        </p>
      </div>
    </div>
    </li>
    </ul>
      <% end %>
    <%else %>
    <p class= "user-text"> You must be registered as an Artist to post artwork </p>

  <% end %>
  </div>
  </div>



                </div>

app/views/users/showWrit.html.erb
<div class="jumb">
  <img class = "image-bubble" src="/images/Collab_bubble_purple.png">
  <h5> <%= @user.username %>'s Writings</h5>
</div>


<!--Navbar -->
<link href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">


	<div class="row">

		<div class="col-md-12">

			<div class="panel panel-default">

                <div class="panel-heading">

                    <span class="panel-title">

						<div class="pull-left">
							<ul class="nav nav-tabs">
								<li class="inactive"><%= link_to "Profile", user_path(@user) %> </li>
								<li class="inactive"><a href="/users/<%= @user.id%>/gallery"><i class="glyphicon glyphicon-picture"></i> Gallery</a></li>
								<li class="active"><a href=""><i class="glyphicon glyphicon-pencil"></i> Writings</a></li>
							</ul>
						</div>

                            <div class="btn-group pull-right">
                                    <% if current_user == @user %>
                                    <%= button_to edit_user_path(@user), :class => "btn btn-default dropdown-toggle", method: "get" do %> Settings <i class="glyphicon glyphicon-cog"></i>
                                    <%end%>
                                    <%end%>
                                <ul class="dropdown-menu" style="width:300px; padding:0px;">

										<li>


												    <div class="panel panel-default" id="preferences" style="margin:0px;">

									    <div class="panel-body">

    										<div class="form-group">

											</div>

										</div>
												</div>
										</li>
									</ul>
                            </div>

						<div class="clearfix"></div>

					</span>

				</div>

                <div class="panel-body">
                <!--Render user writings -->
								<% if @user.person == "Writer" %>
								<h1 class="user-text"><%= @user.username %> 's Writings </h1>
								<% @writings.each do |writing| %>
								<ul>
								<li class="list-group-item">
								Name: <%= writing.name %>
								<br>
								Description: <p class="description"> <%= writing.description %> </p>
								<br>
								 <% if current_user == @user %>
								<%= button_to edit_writing_path(writing), :class => "btn btn-info", method: :get do %> Edit <% end %>
								<% end %>
								</li>
								</ul>
								<% end %>
								<% end %>

                <% if @user.person == "Writer" %>
                <% if current_user == @user %>
                   <!--new button to create a new post-->
                   <div class = "centered">
                <%= button_to new_writing_path, :class => "btn btn-info", method: "get" do %> Add a New Writing Post
									<%end%>
									</div>
                <% elsif current_user == @user %>
                <p> You must be registered as a writer to post writings </p>
                <% else %>
                    <% end %>
                    <% end %>

								</div>






                </div>

app/views/users/update.html.erb
<div class="jumbotron">
  <h1 class="jumbotron-text">New Writing Post Form</h1>
</div>


<%= form_for :user, url: "/users", method: "post" do |f| %>
	  <br>
    About: <%= f.text_field :about, placeholder: "About" %>
    <br>
    <div class = "text-field">
    Technologies/Softwares you use: <%= f.text_field :about, placeholder: "About" %>
    </div>
    <br>
    <%= f.submit "Edit" %>
    <% end %>

app/views/users/users.html.erb
<!-- app/views/users/users.html.erb` -->

<% @users.each do |user| %>

    <div>
        Name: <%= user.username %> <br>
        First Name: <%=  user.first_name %>
    </div>

<p><%= button_to "Log out",  logout_path, method: "destroy" %> </p>

<% end %>