config/routes.rb
Rails.application.routes.draw do
  resources :user_notifications
root to: 'home#show'
resources :users
resources :writings
resources :publishedworks

get "/sign_up", to: "users#new", as: "sign_up"

get "/login", to: "sessions#new"

post "/sessions", to: "sessions#create"

post "/logout", to: "sessions#destroy"

get "/home", to: "home#show"

get "/artists", to: "artists#show"

get "/writers", to: "writers#show"

# post "/publishedworks/new"

# get "/gallery/:user_id", to: "gallery#show"

# get "/works", to: "publishedworks#show"


# get "/users/:id/gallery", to: "gallery#show"

get "/users/:id/gallery", to: "users#showGal"

get "/users/:id/writings", to: "users#showWrit"

delete "/users/:user_id/writings", to: "writings#destroy", as: "destroy_users_writing"

post "/users/:id/connect", to: "users#connect", as: "connect"

get "/request", to: "users#sendReq", as: "request"

get "/users/:id/drawings/new", to: "users#newDraw", as: "draw"





# # commenting out for now - old writNew routes
# get "/users/:id/writings/edit", to: "users#writNew"

# get "/writers/new", to: "writers#new", as: "writings"

# post "/writers/", to: "writers#create"





end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/show.html.erb
<!DOCTYPE html>
<div id = "test-header" class="head-center container">
  <span id="logo-header"> <img style= 'width: 900px; margin-top: -70px' src='/images/Collab_logo.png'></span>

</div>

<div id = "what-we-do" class="head-center">
<h1> What We Do </h1>
<p class="what-info"> When creating comics, you'll need two key skills: good writing and artistic skills. Unfortunately, these skills are mutually exclusive: a great artist can be a terrible writer or the reverse is true: a great writer can be a terrible artist. This is where the idea of Collab-A-Comic comes in, to create a community where comic book writers and artists can find their ideal collaboration partner to work with. </p>
</div
>
<div id= "how-it-works" class="head-center">
  <h1> How it works </h1>
  <img id="howitworks" style = "width: 700px" src="/images/How_it_works.png">
</div>

<div id ="get-started" class="head-center">
  <h1> Getting Started </h1>
<p class="what-info"> Now that you have some familiarity with how the site works, let's get started by checking out the main sections of the site! </p>
<div class="row">
  <%= link_to artists_path do %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail main-wrapper">
      <i class="material-icons">brush</i>
      <div class="caption">
        <h3>Find an Artist</h3>
        <p>Search the site for an artist</p>
      </div>
    </div>
  </div>
  <%end%>
  <%= link_to writers_path do %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail main-wrapper2">
      <i class="material-icons" id="pen">edit</i>
      <div class="caption">
        <h3>Find a Writer</h3>
        <p>Search the site for a writer</p>
      </div>
    </div>
  </div>
  <% end %>
  <%= link_to publishedworks_path do %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail main-wrapper3">
      <i class="material-icons" id="book">import_contacts</i>
      <div class="caption">
        <h3>Read a Comic</h3>
        <p>Check out some of the comics created by the users from Collab-A-Comic!</p>
      </div>
    </div>
  </div>
  <%end %>
</div>

</html>