config/routes.rb
Rails.application.routes.draw do
  resources :user_notifications
root to: 'home#show'
resources :users
resources :writings
resources :publishedworks

get "/sign_up", to: "users#new", as: "sign_up"

get "/login", to: "sessions#new"

post "/sessions", to: "sessions#create"

post "/logout", to: "sessions#destroy"

get "/home", to: "home#show"

get "/artists", to: "artists#show"

get "/writers", to: "writers#show"

# post "/publishedworks/new"

# get "/gallery/:user_id", to: "gallery#show"

# get "/works", to: "publishedworks#show"


# get "/users/:id/gallery", to: "gallery#show"

get "/users/:id/gallery", to: "users#showGal"

get "/users/:id/writings", to: "users#showWrit"

delete "/users/:user_id/writings", to: "writings#destroy", as: "destroy_users_writing"

post "/users/:id/connect", to: "users#connect", as: "connect"

get "/request", to: "users#sendReq", as: "request"

get "/users/:id/drawings/new", to: "users#newDraw", as: "draw"





# # commenting out for now - old writNew routes
# get "/users/:id/writings/edit", to: "users#writNew"

# get "/writers/new", to: "writers#new", as: "writings"

# post "/writers/", to: "writers#create"





end

app/models/user_notification.rb
class UserNotification < ActiveRecord::Base
end

app/controllers/user_notifications_controller.rb
class UserNotificationsController < ApplicationController
  before_action :set_user_notification, only: [:show, :edit, :update, :destroy]

  # GET /user_notifications
  # GET /user_notifications.json
  def index
    @user_notifications = UserNotification.all
  end

  # GET /user_notifications/1
  # GET /user_notifications/1.json
  def show
  end

  # GET /user_notifications/new
  def new
    @user_notification = UserNotification.new
  end

  # GET /user_notifications/1/edit
  def edit
  end

  # POST /user_notifications
  # POST /user_notifications.json
  def create
    @user_notification = UserNotification.new(user_notification_params)

    respond_to do |format|
      if @user_notification.save
        format.html { redirect_to @user_notification, notice: 'User notification was successfully created.' }
        format.json { render :show, status: :created, location: @user_notification }
      else
        format.html { render :new }
        format.json { render json: @user_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_notifications/1
  # PATCH/PUT /user_notifications/1.json
  def update
    respond_to do |format|
      if @user_notification.update(user_notification_params)
        format.html { redirect_to @user_notification, notice: 'User notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_notification }
      else
        format.html { render :edit }
        format.json { render json: @user_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_notifications/1
  # DELETE /user_notifications/1.json
  def destroy
    @user_notification.destroy
    respond_to do |format|
      format.html { redirect_to user_notifications_url, notice: 'User notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_notification
      @user_notification = UserNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_notification_params
      params.require(:user_notification).permit(:name, :email, :login)
    end
end

app/helpers/user_notifications_helper.rb
module UserNotificationsHelper
end

app/views/user_notifications/_form.html.erb
<%= form_for(@user_notification) do |f| %>
  <% if @user_notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_notification.errors.count, "error") %> prohibited this user_notification from being saved:</h2>

      <ul>
      <% @user_notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :login %><br>
    <%= f.text_field :login %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_notifications/edit.html.erb
<h1>Editing User Notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_notification %> |
<%= link_to 'Back', user_notifications_path %>

app/views/user_notifications/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Notifications</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_notifications.each do |user_notification| %>
      <tr>
        <td><%= user_notification.name %></td>
        <td><%= user_notification.email %></td>
        <td><%= user_notification.login %></td>
        <td><%= link_to 'Show', user_notification %></td>
        <td><%= link_to 'Edit', edit_user_notification_path(user_notification) %></td>
        <td><%= link_to 'Destroy', user_notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User notification', new_user_notification_path %>

app/views/user_notifications/new.html.erb
<h1>New User Notification</h1>

<%= render 'form' %>

<%= link_to 'Back', user_notifications_path %>

app/views/user_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user_notification.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_notification.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user_notification.login %>
</p>

<%= link_to 'Edit', edit_user_notification_path(@user_notification) %> |
<%= link_to 'Back', user_notifications_path %>