config/routes.rb
Rails.application.routes.draw do
  resources :user_notifications
root to: 'home#show'
resources :users
resources :writings
resources :publishedworks

get "/sign_up", to: "users#new", as: "sign_up"

get "/login", to: "sessions#new"

post "/sessions", to: "sessions#create"

post "/logout", to: "sessions#destroy"

get "/home", to: "home#show"

get "/artists", to: "artists#show"

get "/writers", to: "writers#show"

# post "/publishedworks/new"

# get "/gallery/:user_id", to: "gallery#show"

# get "/works", to: "publishedworks#show"


# get "/users/:id/gallery", to: "gallery#show"

get "/users/:id/gallery", to: "users#showGal"

get "/users/:id/writings", to: "users#showWrit"

delete "/users/:user_id/writings", to: "writings#destroy", as: "destroy_users_writing"

post "/users/:id/connect", to: "users#connect", as: "connect"

get "/request", to: "users#sendReq", as: "request"

get "/users/:id/drawings/new", to: "users#newDraw", as: "draw"





# # commenting out for now - old writNew routes
# get "/users/:id/writings/edit", to: "users#writNew"

# get "/writers/new", to: "writers#new", as: "writings"

# post "/writers/", to: "writers#create"





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

    def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_auth
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
        if !current_user
          redirect_to root_path
        end
  end
  helper_method :current_user


end

app/helpers/application_helper.rb
module ApplicationHelper

	
end

app/views/application/_nav.html.erb
<!-- Navigation -->
<nav class="navbar-inverse" role="navigation">
  <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
           <!--  <a class="navbar-brand" href="#">
                <img src="http://placehold.it/150x50&text=Logo" alt="">
            </a> -->
               <a class="navbar-brand" href="">
                Collab-a-Comic
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="/home">Home</a>
               </li>
               <% if current_user %>
               <li>
                    <a href="">Logged in as, <%= current_user.username %> </a>
               </li>
               <% end %>
                <% if current_user %>
                <li>
                    <%= link_to "Profile", user_path(current_user) %>
                </li>
                <% end %>
                <li>
                    <a href="/publishedworks">Published Works</a>
                </li>
                <li>
                    <a href="/writers">Find a Writer</a>
                </li>
                <li>
                    <a href="/artists">Find an Artist</a>
                </li>
                <% if !current_user %>
                  <li>
                    <%= link_to "Login", login_path %>
                </li>
                <% end %>
                <% if !current_user %>
                 <li>
                    <%= link_to "Sign Up", sign_up_path %>
                </li>
                <% end %>
                <% if current_user %>
                 <li>
                    <%= link_to "Log Out", logout_path, method: "destroy" %>
                </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<%= bootstrap_flash %>